name: Updated Website on AWS

on: push

jobs:
  update-aws:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Master
        uses: actions/checkout@master
        with: 
          submodules: recursive
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build website
      - run: npm run build
      
      - name: Upload S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'out'
          
#         uses: shallwefootball/s3-upload-action@master
#         with:
#           aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#           aws_bucket: ${{ secrets.AWS_BUCKET }}
#           source_dir: 'src/public'
#           destination_dir: ''
    
      - name: Invalidate Cloudfront Distribution
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "eu-west-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
